# Generated by Django 4.0.1 on 2022-02-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='photo/%y/%m/%d', verbose_name='photo'),
        ),
    ]
